from dataclasses import dataclass
from typing import Dict, Any
import pandas as pd


@dataclass
class CandleSet:
    """Represents a set of daily OHLCV candles for a single symbol."""
    symbol: str
    daily: pd.DataFrame
    
    @property
    def latest_date(self) -> pd.Timestamp:
        """Return the date of the most recent candle."""
        return self.daily.index[-1]


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy."""
    symbol: str
    date: str
    direction: str  # "LONG" or "SHORT"
    entry_price: float
    stop_loss: float
    targets: Dict[str, float]
    metadata: Dict[str, Any]  # Store strategy-specific stats (e.g. RSI value, MACD value)
